import { useState, useEffect, useRef, useCallback } from "react";
const WORKER_URL="https://ict-data-proxy.suketu29.workers.dev";
const IST_OFFSET=5.5*60*60*1000;
const ENV_AI_KEY=process.env.REACT_APP_ANTHROPIC_KEY||"";
function nowIST(){return new Date(Date.now()+IST_OFFSET);}
function pad(n){return String(n).padStart(2,"0");}
function istStr(d){return`${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}:${pad(d.getUTCSeconds())} IST`;}
function toMins(s){const[h,m]=s.split(":").map(Number);return h*60+m;}
function inWin(d,s,e){const c=d.getUTCHours()*60+d.getUTCMinutes(),st=toMins(s),et=toMins(e);return et>st?(c>=st&&c<et):(c>=st||c<et);}
function winPct(d,s,e){const c=d.getUTCHours()*60+d.getUTCMinutes(),st=toMins(s),et=toMins(e);if(et<=st)return 0;return Math.min(100,Math.max(0,Math.round(((c-st)/(et-st))*100)));}
function getT(){const now=new Date(),m=now.getMonth()+1,d=now.getDate();const ukBST=(m>3)||(m===3&&d>=29)||(m<10)||(m===10&&d<25);const usEDT=(m>3)||(m===3&&d>=8)||(m<11)||(m===11&&d<1);if(!ukBST&&usEDT)return{london:{s:"13:30",e:"18:30"},ny:{s:"18:30",e:"00:30"},overlap:{s:"18:30",e:"21:30"},asian:{s:"02:30",e:"06:30"},sb1:{s:"14:00",e:"15:00"},sb2:{s:"20:00",e:"21:00"},sb3:{s:"00:00",e:"01:00"},note:"UK GMT · US EDT"};if(ukBST&&usEDT)return{london:{s:"12:30",e:"17:30"},ny:{s:"18:30",e:"00:30"},overlap:{s:"18:30",e:"21:30"},asian:{s:"02:30",e:"06:30"},sb1:{s:"13:00",e:"14:00"},sb2:{s:"20:00",e:"21:00"},sb3:{s:"00:00",e:"01:00"},note:"UK BST · US EDT"};if(!ukBST&&!usEDT)return{london:{s:"13:30",e:"18:30"},ny:{s:"19:30",e:"01:30"},overlap:{s:"19:30",e:"22:30"},asian:{s:"02:30",e:"06:30"},sb1:{s:"14:00",e:"15:00"},sb2:{s:"21:00",e:"22:00"},sb3:{s:"01:00",e:"02:00"},note:"UK GMT · US EST"};return{london:{s:"12:30",e:"17:30"},ny:{s:"19:30",e:"01:30"},overlap:{s:"19:30",e:"22:30"},asian:{s:"02:30",e:"06:30"},sb1:{s:"13:00",e:"14:00"},sb2:{s:"21:00",e:"22:00"},sb3:{s:"01:00",e:"02:00"},note:"UK BST · US EST"};}
const TF_ORDER=["1m","5m","15m","30m","1H","2H","4H","1D","1W"];
const TF_TD={"1m":"1min","5m":"5min","15m":"15min","30m":"30min","1H":"1h","2H":"2h","4H":"4h","1D":"1day","1W":"1week"};
const ALL_TF=Object.keys(TF_TD);
const tfIdx=tf=>TF_ORDER.indexOf(tf);
const tfMins=tf=>({"1m":1,"5m":5,"15m":15,"30m":30,"1H":60,"2H":120,"4H":240,"1D":1440,"1W":10080}[tf]||15);
function tfWarnings(tfs){const warns=[];const hi=tfIdx(tfs.htf),bi=tfIdx(tfs.bias),ei=tfIdx(tfs.entry),xi=tfIdx(tfs.execution);if(hi<=bi)warns.push(`HTF (${tfs.htf}) must be higher than Bias (${tfs.bias})`);if(bi<=ei)warns.push(`Bias (${tfs.bias}) must be higher than Entry (${tfs.entry})`);if(ei<=xi)warns.push(`Entry (${tfs.entry}) must be higher than Execution (${tfs.execution})`);const gap=ei-xi;if(gap>3)warns.push(`ICT rule: Execution (${tfs.execution}) is ${gap} steps below Entry (${tfs.entry}) — recommended max 2–3 steps. Try: ${TF_ORDER[Math.max(0,ei-2)]} or ${TF_ORDER[Math.max(0,ei-3)]}`);return warns;}
const DEFAULT_TFS={htf:"1D",bias:"4H",entry:"1H",execution:"15m"};
const SYMBOLS={XAUUSD:{label:"Gold",color:"#92400E",accent:"#B45309",bg:"#FFFBEB",border:"#FDE68A",td:"XAU/USD",fallback:3020,vol:0.0018},XAGUSD:{label:"Silver",color:"#374151",accent:"#4B5563",bg:"#F9FAFB",border:"#D1D5DB",td:"XAG/USD",fallback:33.5,vol:0.003},USOIL:{label:"Crude Oil",color:"#9A3412",accent:"#C2410C",bg:"#FFF7ED",border:"#FED7AA",td:"WTI/USD",fallback:71.2,vol:0.003},NATGAS:{label:"Nat Gas",color:"#075985",accent:"#0369A1",bg:"#F0F9FF",border:"#BAE6FD",td:"XNG/USD",fallback:2.18,vol:0.006}};
const SK={brain:"ict_v11_brain",key:"ict_v11_key",aikey:"ict_v11_aikey",cache:"ict_v11_cache",done:"ict_v11_done"};
const ls={get:k=>{try{const r=localStorage.getItem(k);return r?JSON.parse(r):null;}catch{}return null;},set:(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}},str:k=>{try{return localStorage.getItem(k)||"";}catch{}return "";},setStr:(k,v)=>{try{localStorage.setItem(k,v);}catch{}}};
async function wFetch(p){try{const r=await fetch(`${WORKER_URL}?${new URLSearchParams(p)}`);if(!r.ok)throw new Error(`HTTP ${r.status}`);return{data:await r.json(),error:null};}catch(e){return{data:null,error:e.message};}}
async function fetchPrice(sym,key){const{data,error}=await wFetch({symbol:sym,type:"price",apikey:key});if(error||!data?.price)return{price:null,error:error||data?.message};const p=parseFloat(data.price);return{price:isNaN(p)?null:p,error:null};}
async function fetchCandles(sym,interval,key,outputsize=200){const{data,error}=await wFetch({symbol:sym,interval,outputsize,type:"candles",apikey:key});if(error||data?.status==="error"||!data?.values?.length)return{candles:null,error:error||data?.message};return{candles:data.values.map(v=>({t:new Date(v.datetime).getTime(),o:parseFloat(v.open),h:parseFloat(v.high),l:parseFloat(v.low),c:parseFloat(v.close),v:parseFloat(v.volume)||0})),error:null};}
async function testConn(key){const{price,error}=await fetchPrice("XAU/USD",key);return price?{ok:true,msg:`✅ Connected! Gold: $${price.toFixed(2)}`}:{ok:false,msg:`❌ ${error}`};}
const DW={htfBias:{weight:20,wins:0,losses:0,label:"HTF MA Bias",info:"Price vs MA20/MA50 — directional trend filter"},premDisc:{weight:15,wins:0,losses:0,label:"Premium/Discount",info:"ICT: buy in discount, sell in premium zone (50% equilibrium)"},ote:{weight:20,wins:0,losses:0,label:"OTE 62–79% Fib",info:"Optimal Trade Entry — sweet-spot Fibonacci retracement"},bullOB:{weight:25,wins:0,losses:0,label:"Bullish Order Block",info:"Last bearish candle before strong bullish move = demand zone"},bearOB:{weight:25,wins:0,losses:0,label:"Bearish Order Block",info:"Last bullish candle before strong bearish move = supply zone"},bullFVG:{weight:18,wins:0,losses:0,label:"Bullish FVG",info:"Bullish imbalance gap — price likely returns to fill it"},bearFVG:{weight:18,wins:0,losses:0,label:"Bearish FVG",info:"Bearish imbalance gap — price likely returns to fill it"},liqSweep:{weight:22,wins:0,losses:0,label:"Liquidity Sweep",info:"Stop hunt above equal highs / below equal lows — reversal signal"},bosBull:{weight:15,wins:0,losses:0,label:"Bullish BOS",info:"Break of Structure — higher high = bullish trend confirmed"},bosBear:{weight:15,wins:0,losses:0,label:"Bearish BOS",info:"Break of Structure — lower low = bearish trend confirmed"},chochBull:{weight:18,wins:0,losses:0,label:"CHoCH Bullish",info:"Change of Character — first sign of bullish reversal"},chochBear:{weight:18,wins:0,losses:0,label:"CHoCH Bearish",info:"Change of Character — first sign of bearish reversal"},displacement:{weight:12,wins:0,losses:0,label:"Displacement",info:"Strong impulsive candle >2× ATR — institutional order flow"},asianBreak:{weight:10,wins:0,losses:0,label:"Asian Range Break",info:"Price breaks above/below Asian session range — directional signal"}};
const DT={minConfidence:40,minRR:1.0,slMult:1.8,tp1Mult:2.0,tp2Mult:3.5};
function freshBrain(){return{weights:JSON.parse(JSON.stringify(DW)),thresholds:{...DT},kzPerf:Object.fromEntries(Object.keys(SYMBOLS).map(k=>[k,{asian:{w:0,l:0},london:{w:0,l:0},overlap:{w:0,l:0},ny:{w:0,l:0}}])),generations:0,totalTrades:0,overallWinRate:0,learningLog:[]};}
function genCandles(base,mins,count=200,vol=0.0018){const sv=vol*Math.sqrt(mins/15);const out=[];let p=base;const now=Date.now();for(let i=count;i>=0;i--){const chg=(Math.random()-0.499+Math.sin(i*0.04)*0.0002)*p*sv;const o=p;p=Math.max(p+chg,base*0.75);const h=Math.max(o,p)+Math.random()*p*sv*0.3,l=Math.min(o,p)-Math.random()*p*sv*0.3;out.push({t:now-i*mins*60000,o:+o.toFixed(4),h:+h.toFixed(4),l:+l.toFixed(4),c:+p.toFixed(4),v:Math.floor(Math.random()*8000+1000)});}return out;}
function detectOBs(c){const o=[];for(let i=2;i<c.length-3;i++){const a=c[i],b=c[i+1];if(Math.abs(b.c-b.o)>Math.abs(a.c-a.o)*1.6){if(a.c>a.o&&b.c<b.o)o.push({type:"bearish",hi:a.h,lo:a.l});if(a.c<a.o&&b.c>b.o)o.push({type:"bullish",hi:a.h,lo:a.l});}}return o.slice(-6);}
function detectFVGs(c){const f=[];for(let i=1;i<c.length-1;i++){const p=c[i-1],n=c[i+1];if(n.l>p.h)f.push({type:"bullish",top:n.l,bot:p.h,filled:false});if(n.h<p.l)f.push({type:"bearish",top:p.l,bot:n.h,filled:false});}return f.slice(-8);}
function detectStr(c){const s=[];for(let i=3;i<c.length-1;i++){const a=c[i],p=c[i-1],p2=c[i-2];if(a.h>p.h&&a.h>p2.h&&a.c>p.h)s.push({type:"BOS",dir:"bullish",price:a.h});if(a.l<p.l&&a.l<p2.l&&a.c<p.l)s.push({type:"BOS",dir:"bearish",price:a.l});if(p2.c<p2.o&&p.c<p.o&&a.c>p.h)s.push({type:"CHoCH",dir:"bullish",price:a.c});if(p2.c>p2.o&&p.c>p.o&&a.c<p.l)s.push({type:"CHoCH",dir:"bearish",price:a.c});}return s.slice(-6);}
function getLiq(c){const r=c.slice(-40),ph=Math.max(...r.slice(-10,-1).map(x=>x.h)),pl=Math.min(...r.slice(-10,-1).map(x=>x.l)),last=r[r.length-1];return{bsl:Math.max(...r.map(x=>x.h)),ssl:Math.min(...r.map(x=>x.l)),sweepBuy:last.l<pl&&last.c>pl,sweepSell:last.h>ph&&last.c<ph};}
function getPD(c){const r=c.slice(-60),maxH=Math.max(...r.map(x=>x.h)),minL=Math.min(...r.map(x=>x.l)),range=maxH-minL||1,eq=minL+range*0.5,last=c[c.length-1].c;return{zone:last>eq?"PREMIUM":"DISCOUNT",eq:+eq.toFixed(3),inOTE_bull:last>=minL+range*0.62&&last<=minL+range*0.79,inOTE_bear:last>=maxH-range*0.79&&last<=maxH-range*0.62,maxH:+maxH.toFixed(3),minL:+minL.toFixed(3)};}
function getHTF(c){if(c.length<50)return{bias:"NEUTRAL"};const ma20=c.slice(-20).reduce((s,x)=>s+x.c,0)/20,ma50=c.slice(-50).reduce((s,x)=>s+x.c,0)/50,last=c[c.length-1].c;let sc=0;if(last>ma20)sc++;if(last>ma50)sc++;if(ma20>ma50)sc++;return{bias:sc>=2?"BULLISH":sc<=1?"BEARISH":"NEUTRAL"};}
function getAsian(c){const a=c.slice(-20,-10),hi=Math.max(...a.map(x=>x.h)),lo=Math.min(...a.map(x=>x.l));return{hi:+hi.toFixed(3),lo:+lo.toFixed(3)};}
function getDisp(c){const r=c.slice(-10),atr=r.reduce((s,x)=>s+(x.h-x.l),0)/r.length||1,last=r[r.length-1],move=Math.abs(last.c-last.o);return move>atr*2?{found:true,dir:last.c>last.o?"bullish":"bearish"}:{found:false};}
function analyze(candles,weights,thresh){if(!candles?.length)return null;const obs=detectOBs(candles),fvgs=detectFVGs(candles),structs=detectStr(candles),liq=getLiq(candles),pd=getPD(candles),disp=getDisp(candles),htf=getHTF(candles),asian=getAsian(candles);const last=candles[candles.length-1],atr=candles.slice(-14).reduce((s,c)=>s+(c.h-c.l),0)/14||0.1;let bull=0,bear=0;const fr={bull:[],bear:[]};const fire=(k,d)=>{const w=weights[k]?.weight||10;if(d==="bull"){bull+=w;fr.bull.push(k);}else{bear+=w;fr.bear.push(k);}};if(htf.bias==="BULLISH")fire("htfBias","bull");else if(htf.bias==="BEARISH")fire("htfBias","bear");if(pd.zone==="DISCOUNT")fire("premDisc","bull");else fire("premDisc","bear");if(pd.inOTE_bull)fire("ote","bull");if(pd.inOTE_bear)fire("ote","bear");const bOB=obs.find(o=>o.type==="bullish"&&last.c>=o.lo&&last.c<=o.hi*1.003);const beOB=obs.find(o=>o.type==="bearish"&&last.c<=o.hi&&last.c>=o.lo*0.997);if(bOB)fire("bullOB","bull");if(beOB)fire("bearOB","bear");const bF=fvgs.find(f=>f.type==="bullish"&&!f.filled&&last.c>=f.bot&&last.c<=f.top);const beF=fvgs.find(f=>f.type==="bearish"&&!f.filled&&last.c>=f.bot&&last.c<=f.top);if(bF)fire("bullFVG","bull");if(beF)fire("bearFVG","bear");if(liq.sweepBuy)fire("liqSweep","bull");if(liq.sweepSell)fire("liqSweep","bear");const lB=[...structs].reverse().find(s=>s.type==="BOS");const lC=[...structs].reverse().find(s=>s.type==="CHoCH");if(lB?.dir==="bullish")fire("bosBull","bull");if(lB?.dir==="bearish")fire("bosBear","bear");if(lC?.dir==="bullish")fire("chochBull","bull");if(lC?.dir==="bearish")fire("chochBear","bear");if(disp.found){if(disp.dir==="bullish")fire("displacement","bull");else fire("displacement","bear");}if(last.c>asian.hi)fire("asianBreak","bull");else if(last.c<asian.lo)fire("asianBreak","bear");const total=bull+bear||1,dir=bull>=bear?"LONG":"SHORT",conf=Math.min(96,Math.max(38,Math.round(Math.max(bull,bear)/total*100)));const sl=dir==="LONG"?+(last.c-atr*thresh.slMult).toFixed(3):+(last.c+atr*thresh.slMult).toFixed(3);const tp1=dir==="LONG"?+(last.c+atr*thresh.tp1Mult).toFixed(3):+(last.c-atr*thresh.tp1Mult).toFixed(3);const tp2=dir==="LONG"?+(last.c+atr*thresh.tp2Mult).toFixed(3):+(last.c-atr*thresh.tp2Mult).toFixed(3);const rr=+(Math.abs(tp1-last.c)/Math.abs(sl-last.c)).toFixed(2);const RL={htfBias:"HTF MA Bias",premDisc:"Premium/Discount",ote:"OTE 62–79%",bullOB:"Bullish OB",bearOB:"Bearish OB",bullFVG:"Bullish FVG",bearFVG:"Bearish FVG",liqSweep:"Liquidity Sweep",bosBull:"Bullish BOS",bosBear:"Bearish BOS",chochBull:"CHoCH Bullish",chochBear:"CHoCH Bearish",displacement:"Displacement",asianBreak:"Asian Range Break"};return{dir,conf,reasons:fr[dir==="LONG"?"bull":"bear"].map(k=>RL[k]),firedRules:fr,entry:last.c,sl,tp1,tp2,rr,atr:+atr.toFixed(3),obs,fvgs,structs,liq,pd,htf,asian};}
function learnFromBT(prev,trades,winRate,total,sym){const brain=JSON.parse(JSON.stringify(prev));const log=[];if(total===0){log.push("No ICT setups triggered on this data. Try running Analyze first to confirm chart data loaded correctly.");brain.generations++;brain.learningLog=[{gen:brain.generations,sym,date:istStr(nowIST()),winRate:0,totalTrades:0,changes:log},...(brain.learningLog||[])].slice(0,20);return{brain,log};}if(winRate<50&&brain.thresholds.minConfidence<70){const o=brain.thresholds.minConfidence;brain.thresholds.minConfidence=Math.min(70,o+2);log.push(`📈 Win rate ${winRate}% < 50% → Raised min confidence: ${o}% → ${brain.thresholds.minConfidence}%`);}else if(winRate>70&&brain.thresholds.minConfidence>38){const o=brain.thresholds.minConfidence;brain.thresholds.minConfidence=Math.max(38,o-2);log.push(`✅ Win rate ${winRate}% > 70% → Relaxed confidence: ${o}% → ${brain.thresholds.minConfidence}% (more signals)`);}else{log.push(`⚙️ Confidence threshold stable at ${brain.thresholds.minConfidence}%`);}const rs={};Object.keys(brain.weights).forEach(k=>{rs[k]={w:0,l:0};});trades.forEach(t=>{(t.firedRules?.[t.dir==="LONG"?"bull":"bear"]||[]).forEach(rule=>{if(!rs[rule])return;if(t.outcome==="WIN"){rs[rule].w++;brain.weights[rule].wins++;}else{rs[rule].l++;brain.weights[rule].losses++;}});});let changed=0;Object.entries(rs).forEach(([k,s])=>{const rt=s.w+s.l;if(rt<2)return;const wr=s.w/rt,old=brain.weights[k].weight;let nw=old;if(wr>0.70)nw=Math.min(40,Math.round(old*1.15));else if(wr>0.60)nw=Math.min(35,Math.round(old*1.07));else if(wr<0.40)nw=Math.max(4,Math.round(old*0.82));else if(wr<0.50)nw=Math.max(6,Math.round(old*0.93));if(nw!==old){brain.weights[k].weight=nw;log.push(`${nw>old?"↑":"↓"} "${brain.weights[k].label}" ${old}→${nw} (${Math.round(wr*100)}% win rate)`);changed++;}});if(!changed)log.push("⚖️ All ICT rule weights stable — no changes needed");if(!brain.kzPerf[sym])brain.kzPerf[sym]={asian:{w:0,l:0},london:{w:0,l:0},overlap:{w:0,l:0},ny:{w:0,l:0}};trades.forEach(t=>{if(t.kzId&&t.kzId!=="none"&&brain.kzPerf[sym]?.[t.kzId]){if(t.outcome==="WIN")brain.kzPerf[sym][t.kzId].w++;else brain.kzPerf[sym][t.kzId].l++;}});const kzR=Object.entries(brain.kzPerf[sym]).map(([id,s])=>({id,rate:(s.w+s.l>0)?s.w/(s.w+s.l):0.5,trades:s.w+s.l})).filter(k=>k.trades>=1).sort((a,b)=>b.rate-a.rate);if(kzR.length>0)log.push(`🕐 Best session for ${sym}: ${kzR[0].id.toUpperCase()} (${Math.round(kzR[0].rate*100)}% WR, ${kzR[0].trades} trades)`);brain.generations++;brain.totalTrades+=total;brain.overallWinRate=winRate;brain.learningLog=[{gen:brain.generations,sym,date:istStr(nowIST()),winRate,totalTrades:total,changes:log},...(brain.learningLog||[])].slice(0,20);return{brain,log};}
function runBacktest(candles,brain,times){const trades=[];for(let i=60;i<candles.length-10;i++){const a=analyze(candles.slice(i-60,i),brain.weights,brain.thresholds);if(!a||a.rr<brain.thresholds.minRR)continue;const{entry,sl,tp1}=a,ist=new Date(candles[i].t+IST_OFFSET);let kzId="none";if(inWin(ist,times.asian.s,times.asian.e))kzId="asian";else if(inWin(ist,times.overlap.s,times.overlap.e))kzId="overlap";else if(inWin(ist,times.london.s,times.london.e))kzId="london";else if(inWin(ist,times.ny.s,times.ny.e))kzId="ny";let outcome=null,pnl=0;for(const bar of candles.slice(i,i+10)){if(a.dir==="LONG"){if(bar.l<=sl){outcome="LOSS";pnl=+(sl-entry).toFixed(3);break;}if(bar.h>=tp1){outcome="WIN";pnl=+(tp1-entry).toFixed(3);break;}}else{if(bar.h>=sl){outcome="LOSS";pnl=+(entry-sl).toFixed(3);break;}if(bar.l<=tp1){outcome="WIN";pnl=+(entry-tp1).toFixed(3);break;}}}if(outcome)trades.push({...a,outcome,pnl,kzId});}const wins=trades.filter(t=>t.outcome==="WIN").length,losses=trades.filter(t=>t.outcome==="LOSS").length,total=wins+losses;const winRate=total?Math.round(wins/total*100):0;const pf=losses>0?+(trades.filter(t=>t.pnl>0).reduce((s,t)=>s+t.pnl,0)/Math.abs(trades.filter(t=>t.pnl<0).reduce((s,t)=>s+t.pnl,0))).toFixed(2):wins>0?99:0;return{trades:trades.slice(-30),wins,losses,total,winRate,profitFactor:pf,avgRR:total?+(trades.reduce((s,t)=>s+t.rr,0)/total).toFixed(2):0};}
function useClock(){const[t,setT]=useState(nowIST());useEffect(()=>{const id=setInterval(()=>setT(nowIST()),1000);return()=>clearInterval(id);},[]);return t;}

function CandleChart({data,analysis,tfLabel}){
  if(!data?.length)return(<div style={{height:"380px",display:"flex",alignItems:"center",justifyContent:"center",background:"#FAFAFA",borderRadius:"12px",border:"1px solid #E2E8F0"}}><div style={{textAlign:"center",color:"#94A3B8"}}><div style={{fontSize:"36px",marginBottom:"8px"}}>📊</div><div style={{fontSize:"15px",fontWeight:"500"}}>Loading chart data...</div></div></div>);
  const recent=data.slice(-35);
  const maxP=Math.max(...recent.map(c=>c.h)),minP=Math.min(...recent.map(c=>c.l)),range=maxP-minP||1;
  const W=900,H=360,pL=74,pR=60,pT=14,pB=72;
  const cW=W-pL-pR,cH=H-pT-pB;
  const cw=Math.max(cW/recent.length-1.5,3.5);
  const py=v=>pT+cH-((v-minP)/range)*cH;
  const px=i=>pL+i*(cW/recent.length)+cw/2;
  const priceGrid=Array.from({length:6},(_,i)=>minP+(range/5)*i);
  return(
    <div style={{background:"white",borderRadius:"12px",border:"1px solid #E2E8F0",boxShadow:"0 1px 6px rgba(0,0,0,0.05)",overflow:"hidden"}}>
      <div style={{padding:"10px 16px",borderBottom:"1px solid #F1F5F9",display:"flex",justifyContent:"space-between",alignItems:"center",background:"#FAFAFA",flexWrap:"wrap",gap:"8px"}}>
        <span style={{fontWeight:"700",fontSize:"15px",color:"#1E293B"}}>{tfLabel} — Every candle timestamped (IST)</span>
        {analysis&&(<div style={{display:"flex",gap:"12px",alignItems:"center",flexWrap:"wrap"}}>
          <span style={{background:analysis.dir==="LONG"?"#DCFCE7":"#FEE2E2",color:analysis.dir==="LONG"?"#16A34A":"#DC2626",padding:"3px 12px",borderRadius:"20px",fontSize:"13px",fontWeight:"700"}}>{analysis.dir==="LONG"?"▲ LONG":"▼ SHORT"} · {analysis.conf}%</span>
          <span style={{color:"#3B82F6",fontSize:"13px",fontFamily:"monospace"}}>Entry <b>{analysis.entry}</b></span>
          <span style={{color:"#EF4444",fontSize:"13px",fontFamily:"monospace"}}>SL <b>{analysis.sl}</b></span>
          <span style={{color:"#16A34A",fontSize:"13px",fontFamily:"monospace"}}>TP1 <b>{analysis.tp1}</b></span>
        </div>)}
      </div>
      <svg width="100%" viewBox={`0 0 ${W} ${H}`} style={{display:"block",background:"white"}}>
        {priceGrid.map((p,i)=>(<g key={i}><line x1={pL} y1={py(p)} x2={W-pR} y2={py(p)} stroke="#F1F5F9" strokeWidth="1"/><text x={pL-5} y={py(p)+4} textAnchor="end" fill="#94A3B8" fontSize="10.5" fontFamily="monospace">{p>100?p.toFixed(1):p.toFixed(3)}</text></g>))}
        {analysis?.fvgs?.filter(f=>!f.filled).slice(-4).map((f,i)=>(<rect key={i} x={pL} y={py(f.top)} width={cW} height={Math.max(Math.abs(py(f.bot)-py(f.top)),1)} fill={f.type==="bullish"?"rgba(220,252,231,0.4)":"rgba(254,226,226,0.4)"} stroke={f.type==="bullish"?"#86EFAC":"#FCA5A5"} strokeWidth="0.8" strokeDasharray="5,3"/>))}
        {analysis?.obs?.slice(-2).map((ob,i)=>(<rect key={i} x={pL} y={py(ob.hi)} width={cW} height={Math.max(Math.abs(py(ob.lo)-py(ob.hi)),1)} fill={ob.type==="bullish"?"rgba(219,234,254,0.35)":"rgba(254,226,226,0.35)"} stroke={ob.type==="bullish"?"#93C5FD":"#FCA5A5"} strokeWidth="1" strokeDasharray="4,3"/>))}
        {analysis&&<line x1={pL} y1={py(analysis.pd.eq)} x2={W-pR} y2={py(analysis.pd.eq)} stroke="#CBD5E1" strokeWidth="0.8" strokeDasharray="6,4"/>}
        {analysis?.entry&&<><line x1={pL} y1={py(analysis.entry)} x2={W-pR} y2={py(analysis.entry)} stroke="#3B82F6" strokeWidth="2" strokeDasharray="7,4"/><rect x={W-pR+2} y={py(analysis.entry)-10} width={56} height={16} fill="#3B82F6" rx="3"/><text x={W-pR+30} y={py(analysis.entry)+2} textAnchor="middle" fill="white" fontSize="9.5" fontWeight="700">ENTRY</text></>}
        {analysis?.sl&&<><line x1={pL} y1={py(analysis.sl)} x2={W-pR} y2={py(analysis.sl)} stroke="#EF4444" strokeWidth="2" strokeDasharray="5,3"/><rect x={W-pR+2} y={py(analysis.sl)-10} width={38} height={16} fill="#EF4444" rx="3"/><text x={W-pR+21} y={py(analysis.sl)+2} textAnchor="middle" fill="white" fontSize="9.5" fontWeight="700">SL</text></>}
        {analysis?.tp1&&<><line x1={pL} y1={py(analysis.tp1)} x2={W-pR} y2={py(analysis.tp1)} stroke="#16A34A" strokeWidth="2" strokeDasharray="5,3"/><rect x={W-pR+2} y={py(analysis.tp1)-10} width={40} height={16} fill="#16A34A" rx="3"/><text x={W-pR+22} y={py(analysis.tp1)+2} textAnchor="middle" fill="white" fontSize="9.5" fontWeight="700">TP1</text></>}
        {recent.map((c,i)=>{const x=px(i),bull=c.c>=c.o;return(<g key={i}><line x1={x} y1={py(c.h)} x2={x} y2={py(c.l)} stroke={bull?"#16A34A":"#DC2626"} strokeWidth="1.3" opacity="0.8"/><rect x={x-cw/2} y={Math.min(py(c.o),py(c.c))} width={Math.max(cw-1,2)} height={Math.max(Math.abs(py(c.o)-py(c.c)),1.5)} fill={bull?"#16A34A":"#DC2626"} opacity="0.9"/></g>);})}
        {recent.map((c,i)=>{
          const x=px(i),d=new Date(c.t+IST_OFFSET);
          const hhmm=`${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}`;
          const ddmm=`${pad(d.getUTCDate())}/${pad(d.getUTCMonth()+1)}`;
          const prev=i>0?new Date(recent[i-1].t+IST_OFFSET):null;
          const dayChange=!prev||prev.getUTCDate()!==d.getUTCDate();
          return(<g key={`t${i}`}>
            <line x1={x} y1={pT+cH} x2={x} y2={pT+cH+4} stroke="#E2E8F0" strokeWidth="1"/>
            <text x={x} y={pT+cH+16} textAnchor="middle" fill="#475569" fontSize="9.5" fontFamily="monospace" fontWeight={dayChange?"700":"400"}>{hhmm}</text>
            {dayChange&&<text x={x} y={pT+cH+32} textAnchor="middle" fill="#94A3B8" fontSize="8.5" fontFamily="monospace">{ddmm}</text>}
          </g>);
        })}
        <line x1={pL} y1={pT+cH} x2={W-pR} y2={pT+cH} stroke="#E2E8F0" strokeWidth="1.5"/>
        <line x1={pL} y1={pT} x2={pL} y2={pT+cH} stroke="#E2E8F0" strokeWidth="1.5"/>
      </svg>
    </div>
  );
}

function SetupScreen({onSave,times}){
  const[tdKey,setTdKey]=useState(ls.str(SK.key));
  const[aiKey,setAiKey]=useState(ls.str(SK.aikey)||ENV_AI_KEY);
  const[testing,setTesting]=useState(false);
  const[result,setResult]=useState(null);
  const doTest=async()=>{if(!tdKey.trim()){setResult({ok:false,msg:"Enter your Twelve Data key first"});return;}setTesting(true);setResult(null);const r=await testConn(tdKey.trim());setResult(r);setTesting(false);};
  const doSave=()=>{ls.setStr(SK.key,tdKey.trim());ls.setStr(SK.aikey,aiKey.trim());ls.setStr(SK.done,"1");onSave(tdKey.trim(),aiKey.trim());};
  return(
    <div style={{minHeight:"100vh",background:"#F1F5F9",display:"flex",alignItems:"center",justifyContent:"center",padding:"20px",fontFamily:"'Inter','Segoe UI',sans-serif"}}>
      <div style={{maxWidth:"540px",width:"100%",background:"white",borderRadius:"20px",padding:"36px",boxShadow:"0 4px 24px rgba(0,0,0,0.08)",border:"1px solid #E2E8F0"}}>
        <div style={{textAlign:"center",marginBottom:"26px"}}>
          <div style={{width:"64px",height:"64px",background:"linear-gradient(135deg,#1D4ED8,#7C3AED)",borderRadius:"16px",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"30px",margin:"0 auto 12px"}}>🥇</div>
          <div style={{fontWeight:"800",fontSize:"22px",color:"#1E293B"}}>ICT Trading Agent</div>
          <div style={{color:"#64748B",fontSize:"14px",marginTop:"4px"}}>Mumbai, India · One-time setup — keys saved permanently</div>
        </div>
        <div style={{background:"#F0FDF4",border:"1px solid #BBF7D0",borderRadius:"10px",padding:"10px 14px",marginBottom:"14px"}}><div style={{color:"#16A34A",fontSize:"13px",fontWeight:"600"}}>✅ Cloudflare Worker: {WORKER_URL.replace("https://","")}</div></div>
        <div style={{background:"#EFF6FF",borderRadius:"10px",padding:"12px",border:"1px solid #BFDBFE",marginBottom:"20px"}}>
          <div style={{color:"#1D4ED8",fontSize:"13px",fontWeight:"700",marginBottom:"8px"}}>🕐 Session Times — IST ({times.note})</div>
          {[{l:"London Open KZ",s:times.london.s,e:times.london.e,c:"#2563EB"},{l:"London–NY Overlap",s:times.overlap.s,e:times.overlap.e,c:"#059669"},{l:"NY Session",s:times.ny.s,e:times.ny.e,c:"#D97706"},{l:"Silver Bullet 2 (NY)",s:times.sb2.s,e:times.sb2.e,c:"#7C3AED"}].map(row=>(<div key={row.l} style={{display:"flex",justifyContent:"space-between",padding:"3px 0",borderBottom:"1px solid #DBEAFE"}}><span style={{color:row.c,fontSize:"13px",fontWeight:"500"}}>● {row.l}</span><span style={{color:"#1E293B",fontSize:"13px",fontFamily:"monospace",fontWeight:"700"}}>{row.s} – {row.e} IST</span></div>))}
        </div>
        <div style={{marginBottom:"14px"}}>
          <label style={{display:"block",color:"#374151",fontSize:"13px",fontWeight:"700",marginBottom:"6px"}}>📡 TWELVE DATA KEY <span style={{color:"#94A3B8",fontWeight:"400"}}>(real Gold/Silver/Oil/Gas prices)</span></label>
          <input value={tdKey} onChange={e=>setTdKey(e.target.value)} placeholder="Paste Twelve Data API key..." type="password" style={{width:"100%",background:"#F8FAFC",border:"2px solid #E2E8F0",borderRadius:"10px",padding:"11px 14px",color:"#1E293B",fontSize:"14px",outline:"none",fontFamily:"monospace",boxSizing:"border-box"}} onFocus={e=>e.target.style.borderColor="#3B82F6"} onBlur={e=>e.target.style.borderColor="#E2E8F0"}/>
        </div>
        <div style={{marginBottom:"14px"}}>
          <label style={{display:"block",color:"#374151",fontSize:"13px",fontWeight:"700",marginBottom:"6px"}}>🤖 ANTHROPIC KEY <span style={{color:"#94A3B8",fontWeight:"400"}}>(AI chat analyst — from console.anthropic.com)</span></label>
          <input value={aiKey} onChange={e=>setAiKey(e.target.value)} placeholder="sk-ant-api03-..." type="password" style={{width:"100%",background:"#F8FAFC",border:"2px solid #E2E8F0",borderRadius:"10px",padding:"11px 14px",color:"#1E293B",fontSize:"14px",outline:"none",fontFamily:"monospace",boxSizing:"border-box"}} onFocus={e=>e.target.style.borderColor="#7C3AED"} onBlur={e=>e.target.style.borderColor="#E2E8F0"}/>
          <div style={{color:"#94A3B8",fontSize:"12px",marginTop:"4px"}}>Both keys are saved locally in your browser. Never shared or uploaded anywhere.</div>
        </div>
        {result&&<div style={{background:result.ok?"#F0FDF4":"#FEF2F2",border:`1.5px solid ${result.ok?"#86EFAC":"#FCA5A5"}`,borderRadius:"8px",padding:"10px 14px",marginBottom:"12px"}}><span style={{color:result.ok?"#16A34A":"#DC2626",fontSize:"14px",fontWeight:"600"}}>{result.msg}</span></div>}
        <div style={{display:"flex",gap:"10px"}}>
          <button onClick={doTest} disabled={testing||!tdKey.trim()} style={{flex:1,background:"#F1F5F9",border:"2px solid #E2E8F0",color:"#374151",borderRadius:"10px",padding:"12px",fontSize:"14px",fontWeight:"600",cursor:"pointer",opacity:!tdKey.trim()||testing?0.5:1}}>{testing?"Testing...":"🔌 Test Gold Price"}</button>
          <button onClick={doSave} style={{flex:2,background:"linear-gradient(135deg,#1D4ED8,#7C3AED)",color:"white",border:"none",borderRadius:"10px",padding:"12px",fontSize:"14px",fontWeight:"700",cursor:"pointer",boxShadow:"0 2px 10px rgba(29,78,216,0.3)"}}>✅ Save & Launch (Permanent)</button>
        </div>
        <div style={{textAlign:"center",marginTop:"12px"}}><button onClick={()=>onSave("","")} style={{background:"transparent",border:"none",color:"#9CA3AF",fontSize:"13px",cursor:"pointer",textDecoration:"underline"}}>Skip — simulated data only</button></div>
      </div>
    </div>
  );
}

export default function App(){
  const times=getT();
  const KZS=[{id:"asian",name:"Asian Range",start:times.asian.s,end:times.asian.e,color:"#7C3AED",desc:"Consolidation — builds liquidity"},{id:"london",name:"London Open KZ",start:times.london.s,end:times.london.e,color:"#2563EB",desc:"Primary trend & reversal"},{id:"overlap",name:"London–NY Overlap",start:times.overlap.s,end:times.overlap.e,color:"#059669",desc:"Highest volume — best setups"},{id:"ny",name:"NY Session",start:times.ny.s,end:times.ny.e,color:"#D97706",desc:"Continuation & reversal"}];
  const SBS=[{label:"London SB",start:times.sb1.s,end:times.sb1.e},{label:"NY Open SB",start:times.sb2.s,end:times.sb2.e},{label:"NY PM SB",start:times.sb3.s,end:times.sb3.e}];
  const[tdKey,setTdKey]=useState(ls.str(SK.key));
  const[aiKey,setAiKey]=useState(()=>ls.str(SK.aikey)||ENV_AI_KEY);
  const[showSetup,setShowSetup]=useState(()=>ls.str(SK.done)!=="1");
  const[brain,setBrain]=useState(()=>ls.get(SK.brain)||freshBrain());
  const[sym,setSym]=useState("XAUUSD");
  const[selTFs,setSelTFs]=useState(DEFAULT_TFS);
  const[tab,setTab]=useState("signal");
  const[candleData,setCandleData]=useState({});
  const[prices,setPrices]=useState({});
  const[changes,setChanges]=useState({});
  const[symStatus,setSymStatus]=useState({});
  const[loadMsg,setLoadMsg]=useState("");
  const[analysis,setAnalysis]=useState(null);
  const[btResult,setBtResult]=useState(null);
  const[learnLog,setLearnLog]=useState([]);
  const[analyzing,setAnalyzing]=useState(false);
  const[bting,setBting]=useState(false);
  const[learning,setLearning]=useState(false);
  const[lastFetch,setLastFetch]=useState(null);
  const[refreshing,setRefreshing]=useState(false);
  const[tfWarns,setTfWarns]=useState([]);
  const[chat,setChat]=useState([{role:"assistant",content:`🥇 ICT Agent v11 — Mumbai IST (${times.note})\n\nLondon: ${times.london.s}–${times.london.e} IST\nNY: ${times.ny.s}–${times.ny.e} IST\n\n${ls.str(SK.done)==="1"?"Loading real market data for all symbols...":"Add your API keys to get started."}\n\nChart timestamps on every candle. BT+Learn now works with any number of trades.`}]);
  const[chatInput,setChatInput]=useState("");
  const[chatLoading,setChatLoading]=useState(false);
  const istNow=useClock();
  const chatRef=useRef(null);
  const activeKZ=KZS.find(kz=>inWin(istNow,kz.start,kz.end));
  const activeSB=SBS.find(sb=>inWin(istNow,sb.start,sb.end));
  const liveCount=Object.values(symStatus).filter(s=>s==="live").length;
  const isLive=liveCount>0;
  useEffect(()=>{setTfWarns(tfWarnings(selTFs));},[selTFs]);
  const loadAll=useCallback(async(key)=>{const cache=ls.get(SK.cache)||{};for(const[sk,sv] of Object.entries(SYMBOLS)){setSymStatus(p=>({...p,[sk]:"loading"}));setLoadMsg(`Loading ${sk}... (~2 min total)`);const nd={};if(key){const acts=[...new Set([selTFs.execution,selTFs.entry])];for(const tfKey of acts){const ck=`${sk}_${tfKey}`,cached=cache[ck];if(cached?.candles?.length&&(Date.now()-cached.fetchedAt)<20*60*1000){nd[tfKey]=cached.candles;}else{await new Promise(r=>setTimeout(r,9000));const{candles}=await fetchCandles(sv.td,TF_TD[tfKey],key,200);if(candles?.length){nd[tfKey]=candles;cache[ck]={candles,fetchedAt:Date.now()};}else nd[tfKey]=genCandles(sv.fallback,tfMins(tfKey),200,sv.vol);}}ALL_TF.forEach(tf=>{if(!nd[tf])nd[tf]=genCandles(sv.fallback,tfMins(tf),200,sv.vol);});await new Promise(r=>setTimeout(r,3000));const{price}=await fetchPrice(sv.td,key);const p=price||(nd[selTFs.execution]?.slice(-1)[0]?.c)||sv.fallback;setPrices(prev=>({...prev,[sk]:p}));setChanges(prev=>({...prev,[sk]:+(((p-sv.fallback)/sv.fallback)*100).toFixed(2)}));setSymStatus(prev=>({...prev,[sk]:price?"live":"error"}));}else{ALL_TF.forEach(tf=>{nd[tf]=genCandles(sv.fallback,tfMins(tf),200,sv.vol);});const p=nd["15m"].slice(-1)[0]?.c||sv.fallback;setPrices(prev=>({...prev,[sk]:p}));setChanges(prev=>({...prev,[sk]:+(((p-sv.fallback)/sv.fallback)*100).toFixed(2)}));setSymStatus(prev=>({...prev,[sk]:"sim"}));}setCandleData(prev=>({...prev,[sk]:nd}));}if(key)ls.set(SK.cache,cache);setLastFetch(new Date());setLoadMsg("");},[selTFs]);
  useEffect(()=>{if(!showSetup)loadAll(tdKey);},[showSetup,tdKey]);
  const handleRefresh=useCallback(async()=>{if(refreshing||loadMsg)return;setRefreshing(true);setLoadMsg("Refreshing all prices...");for(const[sk,sv] of Object.entries(SYMBOLS)){if(tdKey){const{price}=await fetchPrice(sv.td,tdKey);if(price){setPrices(p=>({...p,[sk]:price}));setChanges(p=>({...p,[sk]:+(((price-sv.fallback)/sv.fallback)*100).toFixed(2)}));setSymStatus(p=>({...p,[sk]:"live"}));}await new Promise(r=>setTimeout(r,8000));}}setLastFetch(new Date());setLoadMsg("");setRefreshing(false);},[tdKey,refreshing,loadMsg]);
  useEffect(()=>{if(!tdKey||showSetup)return;const id=setInterval(handleRefresh,90000);return()=>clearInterval(id);},[tdKey,showSetup,handleRefresh]);
  useEffect(()=>{if(tdKey||showSetup)return;const id=setInterval(()=>{setPrices(prev=>{const n={...prev},ch={};Object.entries(SYMBOLS).forEach(([k,v])=>{n[k]=+(prev[k]*(1+(Math.random()-0.4995)*v.vol*0.4)).toFixed(k==="NATGAS"?3:2);ch[k]=+(((n[k]-v.fallback)/v.fallback)*100).toFixed(2);});setChanges(ch);return n;});},2000);return()=>clearInterval(id);},[tdKey,showSetup]);
  useEffect(()=>{chatRef.current?.scrollIntoView({behavior:"smooth"});},[chat]);
  const handleAnalyze=async()=>{const cd=candleData[sym]?.[selTFs.execution];if(!cd?.length)return;setAnalyzing(true);await new Promise(r=>setTimeout(r,300));setAnalysis(analyze(cd,brain.weights,brain.thresholds));setTab("signal");setAnalyzing(false);};
  const handleBTLearn=async()=>{const cd=candleData[sym]?.[selTFs.execution];if(!cd?.length)return;setBting(true);await new Promise(r=>setTimeout(r,400));const bt=runBacktest(cd,brain,times);setBtResult(bt);setBting(false);setLearning(true);await new Promise(r=>setTimeout(r,500));const{brain:nb,log}=learnFromBT(brain,bt.trades,bt.winRate,bt.total,sym);setBrain(nb);ls.set(SK.brain,nb);setLearnLog(log);setLearning(false);setTab("learning");};
  const handleChat=async()=>{if(!chatInput.trim())return;const effectiveKey=aiKey||ls.str(SK.aikey)||ENV_AI_KEY;if(!effectiveKey){setChat(p=>[...p,{role:"user",content:chatInput},{role:"assistant",content:"⚠️ No Anthropic API key found.\n\nTo fix this:\n1. Click ⚙️ Settings top right\n2. Enter your Anthropic key (get it from console.anthropic.com → API Keys)\n3. Click Save\n\nThe key will be saved permanently — you only need to do this once."}]);setChatInput("");return;}const msg=chatInput.trim();setChatInput("");setChat(p=>[...p,{role:"user",content:msg}]);setChatLoading(true);try{const sys=`Elite ICT commodities analyst for Mumbai trader. Always use IST. Now: ${istStr(istNow)} (${times.note}). London: ${times.london.s}–${times.london.e} IST. NY: ${times.ny.s}–${times.ny.e} IST. Active session: ${activeKZ?.name||"none"}. Silver Bullet: ${activeSB?.label||"none"}. ${sym}@${prices[sym]}. Data: ${isLive?`REAL Twelve Data (${liveCount}/4 live)`:"Simulated"}. Gen${brain.generations}. ${analysis?`Signal: ${analysis.dir} ${analysis.conf}% | Entry:${analysis.entry} SL:${analysis.sl} TP:${analysis.tp1} R:R:${analysis.rr} | Confluences: ${analysis.reasons.join(", ")}`:"No signal yet."} Deep ICT: OBs, FVGs, BOS/CHoCH, Liquidity sweeps, AMD cycle, OTE, Killzones, Silver Bullet.`;const res=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":effectiveKey,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:1000,system:sys,messages:chat.filter(m=>m.role==="user"||m.role==="assistant").concat([{role:"user",content:msg}])})});if(!res.ok){const err=await res.text();throw new Error(`API ${res.status}: ${err.slice(0,120)}`);}const data=await res.json();setChat(p=>[...p,{role:"assistant",content:data.content?.find(b=>b.type==="text")?.text||"No response."}]);}catch(e){setChat(p=>[...p,{role:"assistant",content:`⚠️ Chat error: ${e.message}\n\nCheck your Anthropic API key in ⚙️ Settings.`}]);}setChatLoading(false);};
  const handleSaveSetup=(td,ai)=>{setTdKey(td);setAiKey(ai);setShowSetup(false);};
  if(showSetup)return <SetupScreen onSave={handleSaveSetup} times={times}/>;
  const S=SYMBOLS[sym];
  const TABS=["signal","sessions","weights","learning","backtest"];
  const badge=st=>{if(st==="live")return{bg:"#F0FDF4",color:"#16A34A",border:"#BBF7D0",text:"● LIVE"};if(st==="loading")return{bg:"#FFFBEB",color:"#D97706",border:"#FDE047",text:"⟳"};if(st==="error")return{bg:"#FEF2F2",color:"#DC2626",border:"#FECACA",text:"⚠ ERR"};return{bg:"#F1F5F9",color:"#64748B",border:"#E2E8F0",text:"◌ SIM"};};
  return(
    <div style={{background:"#F1F5F9",minHeight:"100vh",fontFamily:"'Inter','Segoe UI',sans-serif",color:"#1E293B"}}>
      <div style={{background:"white",borderBottom:"2px solid #E2E8F0",padding:"0 16px",display:"flex",alignItems:"stretch",boxShadow:"0 2px 8px rgba(0,0,0,0.05)",flexWrap:"wrap"}}>
        <div style={{display:"flex",alignItems:"center",gap:"10px",padding:"10px 16px 10px 0",borderRight:"2px solid #F1F5F9",marginRight:"12px"}}>
          <div style={{width:"38px",height:"38px",background:"linear-gradient(135deg,#1D4ED8,#7C3AED)",borderRadius:"10px",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"20px"}}>🥇</div>
          <div><div style={{fontWeight:"800",fontSize:"15px"}}>ICT AGENT</div><div style={{fontSize:"11px",color:"#64748B"}}>Mumbai · v11</div></div>
        </div>
        {Object.entries(SYMBOLS).map(([k,v])=>{const st=symStatus[k]||"sim",active=sym===k,p=prices[k],ch=changes[k]||0,b=badge(st);return(<div key={k} onClick={()=>{setSym(k);setAnalysis(null);}} style={{cursor:"pointer",padding:"8px 14px",borderBottom:`3px solid ${active?v.accent:"transparent"}`,background:active?v.bg:"transparent",minWidth:"130px",display:"flex",flexDirection:"column",justifyContent:"center",borderRight:"1px solid #F8FAFC"}}><div style={{display:"flex",alignItems:"center",gap:"5px",marginBottom:"2px"}}><span style={{fontSize:"12px",fontWeight:"700",color:active?v.color:"#64748B",letterSpacing:"0.5px"}}>{k}</span><span style={{fontSize:"10px",padding:"1px 5px",borderRadius:"4px",fontWeight:"600",background:b.bg,color:b.color,border:`1px solid ${b.border}`}}>{b.text}</span></div><div style={{fontWeight:"800",fontSize:"19px",color:active?v.color:"#1E293B",fontFamily:"monospace",letterSpacing:"-0.5px"}}>{p!=null?Number(p).toFixed(k==="NATGAS"?3:2):"—"}</div><div style={{fontSize:"12px",fontWeight:"600",color:ch>=0?"#16A34A":"#DC2626"}}>{ch>=0?"▲":"▼"} {Math.abs(ch).toFixed(2)}%</div></div>);})}
        <div style={{display:"flex",gap:"8px",alignItems:"center",padding:"0 14px",borderLeft:"2px solid #F1F5F9",marginLeft:"6px"}}>
          {[{role:"htf",color:"#7C3AED",tip:"HTF: sets overall bias. Must be highest TF."},{role:"bias",color:"#2563EB",tip:"Bias: confirms direction. 2nd highest."},{role:"entry",color:"#D97706",tip:"Entry: where you identify the ICT setup (e.g. 1H OB)."},{role:"execution",color:"#16A34A",tip:"Execution: precise trigger. ICT rule: max 2-3 steps below Entry TF."}].map(({role,color,tip})=>(<div key={role} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:"2px"}} title={tip}><span style={{fontSize:"9px",fontWeight:"700",color,textTransform:"uppercase",letterSpacing:"0.5px"}}>{role}</span><select value={selTFs[role]} onChange={e=>setSelTFs(p=>({...p,[role]:e.target.value}))} style={{background:`${color}12`,border:`2px solid ${color}44`,color,borderRadius:"7px",padding:"4px 6px",fontSize:"13px",fontWeight:"700",cursor:"pointer",outline:"none",fontFamily:"monospace",minWidth:"52px"}}>{ALL_TF.map(tf=><option key={tf} value={tf}>{tf}</option>)}</select></div>))}
        </div>
        <div style={{marginLeft:"auto",display:"flex",alignItems:"center",gap:"8px",padding:"8px 0 8px 12px"}}>
          {loadMsg&&<div style={{background:"#FFFBEB",border:"1px solid #FDE047",borderRadius:"7px",padding:"4px 10px",fontSize:"12px",color:"#92400E",maxWidth:"200px"}}>{loadMsg}</div>}
          {activeKZ&&<div style={{background:`${activeKZ.color}12`,border:`1.5px solid ${activeKZ.color}44`,borderRadius:"7px",padding:"4px 10px",fontSize:"12px",color:activeKZ.color,fontWeight:"700"}}>● {activeKZ.name}</div>}
          {activeSB&&<div style={{background:"#F5F3FF",border:"1.5px solid #DDD6FE",borderRadius:"7px",padding:"4px 10px",fontSize:"12px",color:"#7C3AED",fontWeight:"700"}}>🥈 {activeSB.label}</div>}
          <div style={{textAlign:"right"}}><div style={{fontWeight:"700",fontSize:"15px",color:"#1D4ED8",fontFamily:"monospace"}}>{istStr(istNow)}</div><div style={{fontSize:"10px",color:"#94A3B8"}}>{times.note}{lastFetch?` · ${pad(new Date(lastFetch.getTime()+IST_OFFSET).getUTCHours())}:${pad(new Date(lastFetch.getTime()+IST_OFFSET).getUTCMinutes())} IST`:""}</div></div>
          <button onClick={handleRefresh} disabled={refreshing||!!loadMsg} style={{background:refreshing?"#F1F5F9":"#EFF6FF",border:"2px solid #BFDBFE",color:refreshing?"#94A3B8":"#1D4ED8",borderRadius:"9px",padding:"7px 14px",fontSize:"13px",fontWeight:"700",cursor:refreshing?"wait":"pointer",display:"flex",alignItems:"center",gap:"5px",whiteSpace:"nowrap"}}>{refreshing?"⟳ Refreshing...":"↺ Refresh Prices"}</button>
          <button onClick={()=>setShowSetup(true)} style={{background:tdKey?"#F0FDF4":"#FFFBEB",border:`2px solid ${tdKey?"#BBF7D0":"#FDE047"}`,color:tdKey?"#16A34A":"#92400E",borderRadius:"9px",padding:"7px 14px",fontSize:"13px",fontWeight:"700",cursor:"pointer"}}>⚙️ {tdKey?`Live (${liveCount}/4)`:"Add Keys"}</button>
        </div>
      </div>
      {tfWarns.length>0&&(<div style={{background:"#FFFBEB",borderBottom:"1px solid #FDE047",padding:"6px 16px",display:"flex",gap:"16px",flexWrap:"wrap"}}>{tfWarns.map((w,i)=><span key={i} style={{fontSize:"12px",color:"#92400E",fontWeight:"500"}}>⚠️ {w}</span>)}</div>)}
      <div style={{display:"grid",gridTemplateColumns:"1fr 400px",height:`calc(100vh - ${74+(tfWarns.length>0?34:0)}px)`}}>
        <div style={{overflowY:"auto",padding:"14px",display:"flex",flexDirection:"column",gap:"10px"}}>
          {!tdKey&&(<div style={{background:"#FFFBEB",border:"2px solid #FDE047",borderRadius:"10px",padding:"10px 16px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:"700",fontSize:"14px",color:"#92400E"}}>◌ Simulated data</div><div style={{color:"#A16207",fontSize:"13px"}}>Add API keys for real prices</div></div><button onClick={()=>setShowSetup(true)} style={{background:"#D97706",color:"white",border:"none",borderRadius:"8px",padding:"7px 14px",fontSize:"13px",fontWeight:"700",cursor:"pointer"}}>Add Keys →</button></div>)}
          <div style={{background:"white",borderRadius:"12px",padding:"14px 18px",border:"1px solid #E2E8F0",display:"flex",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap",gap:"10px",boxShadow:"0 1px 4px rgba(0,0,0,0.04)"}}>
            <div style={{display:"flex",alignItems:"center",gap:"14px"}}>
              <div style={{background:S.bg,border:`2px solid ${S.border}`,borderRadius:"10px",padding:"10px 16px"}}><div style={{fontWeight:"700",fontSize:"12px",color:S.color,letterSpacing:"1px"}}>{sym}</div><div style={{fontWeight:"800",fontSize:"24px",color:S.accent,fontFamily:"monospace",letterSpacing:"-1px"}}>{prices[sym]!=null?Number(prices[sym]).toFixed(sym==="NATGAS"?3:2):"—"}</div><div style={{fontSize:"13px",fontWeight:"600",color:changes[sym]>=0?"#16A34A":"#DC2626"}}>{changes[sym]>=0?"▲":"▼"} {Math.abs(changes[sym]||0).toFixed(2)}%</div></div>
              {analysis&&(<div style={{padding:"10px 14px",background:analysis.dir==="LONG"?"#F0FDF4":"#FEF2F2",borderRadius:"10px",border:`1.5px solid ${analysis.dir==="LONG"?"#86EFAC":"#FCA5A5"}`}}><div style={{fontWeight:"800",fontSize:"18px",color:analysis.dir==="LONG"?"#16A34A":"#DC2626"}}>{analysis.dir==="LONG"?"▲ LONG":"▼ SHORT"}</div><div style={{fontSize:"13px",color:"#64748B"}}>{analysis.conf}% confidence · R:R {analysis.rr}</div></div>)}
            </div>
            <div style={{display:"flex",gap:"8px"}}>
              <button onClick={handleAnalyze} disabled={analyzing} style={{background:"linear-gradient(135deg,#1D4ED8,#4338CA)",color:"white",border:"none",borderRadius:"10px",padding:"11px 22px",fontWeight:"700",fontSize:"14px",cursor:"pointer",opacity:analyzing?0.6:1,boxShadow:"0 2px 10px rgba(29,78,216,0.25)"}}>{analyzing?"⚙️ Analyzing...":"🔬 Analyze"}</button>
              <button onClick={handleBTLearn} disabled={bting||learning} style={{background:"linear-gradient(135deg,#7C3AED,#9333EA)",color:"white",border:"none",borderRadius:"10px",padding:"11px 22px",fontWeight:"700",fontSize:"14px",cursor:"pointer",opacity:(bting||learning)?0.6:1,boxShadow:"0 2px 10px rgba(124,58,237,0.25)"}}>{learning?"🧠 Learning...":(bting?"⚙️ Running...":"🧠 BT + Learn")}</button>
            </div>
          </div>
          <CandleChart data={candleData[sym]?.[selTFs.execution]} analysis={analysis} tfLabel={`${sym} · ${selTFs.execution} · ${isLive?`${liveCount}/4 Live`:"Simulated"}`}/>
          <div style={{background:"white",borderRadius:"10px",padding:"4px",border:"1px solid #E2E8F0",display:"flex",gap:"2px"}}>
            {TABS.map(t=>(<button key={t} onClick={()=>setTab(t)} style={{flex:1,padding:"9px 4px",borderRadius:"7px",border:"none",background:tab===t?"#EFF6FF":"transparent",color:tab===t?"#1D4ED8":"#64748B",fontSize:"13px",fontWeight:tab===t?"700":"500",cursor:"pointer"}}>{t==="signal"?"📡 Signal":t==="sessions"?"🕐 Sessions":t==="weights"?"⚖️ Weights":t==="learning"?"🧠 Learn":"📊 Backtest"}</button>))}
          </div>
          {tab==="signal"&&analysis&&(<div style={{background:"white",borderRadius:"12px",padding:"18px",border:`2px solid ${analysis.dir==="LONG"?"#86EFAC":"#FCA5A5"}`}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"10px",marginBottom:"14px"}}>{[{l:"ENTRY",v:analysis.entry,c:"#1D4ED8",bg:"#EFF6FF",border:"#BFDBFE"},{l:"STOP LOSS",v:analysis.sl,c:"#DC2626",bg:"#FEF2F2",border:"#FECACA"},{l:"TP 1",v:analysis.tp1,c:"#16A34A",bg:"#F0FDF4",border:"#86EFAC"},{l:"TP 2",v:analysis.tp2,c:"#059669",bg:"#F0FDF4",border:"#6EE7B7"}].map(x=>(<div key={x.l} style={{background:x.bg,borderRadius:"10px",padding:"12px",textAlign:"center",border:`1.5px solid ${x.border}`}}><div style={{color:"#64748B",fontSize:"11px",fontWeight:"600",letterSpacing:"0.5px",marginBottom:"5px"}}>{x.l}</div><div style={{color:x.c,fontWeight:"800",fontSize:"17px",fontFamily:"monospace"}}>{x.v}</div></div>))}</div><div style={{display:"flex",gap:"16px",padding:"10px 14px",background:"#F8FAFC",borderRadius:"8px",marginBottom:"14px",flexWrap:"wrap"}}><span style={{fontSize:"14px"}}>R:R <strong style={{color:"#1D4ED8"}}>{analysis.rr}</strong></span><span style={{fontSize:"14px"}}>ATR <strong style={{color:"#7C3AED"}}>{analysis.atr}</strong></span><span style={{fontSize:"14px"}}>Conf <strong style={{color:analysis.conf>=65?"#16A34A":"#D97706"}}>{analysis.conf}%</strong></span><span style={{fontSize:"14px"}}>Gen <strong style={{color:"#7C3AED"}}>{brain.generations}</strong></span>{activeKZ&&<span style={{fontSize:"14px",color:activeKZ.color,fontWeight:"700"}}>● {activeKZ.name}</span>}</div><div style={{borderTop:"1px solid #F1F5F9",paddingTop:"12px"}}><div style={{fontSize:"12px",fontWeight:"700",color:"#94A3B8",marginBottom:"8px"}}>ICT CONFLUENCES ({analysis.reasons.length})</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"7px"}}>{analysis.reasons.map((r,i)=>(<div key={i} style={{display:"flex",gap:"7px",alignItems:"center",background:analysis.dir==="LONG"?"#F0FDF4":"#FEF2F2",padding:"7px 10px",borderRadius:"7px",border:`1px solid ${analysis.dir==="LONG"?"#BBF7D0":"#FECACA"}`}}><span style={{color:analysis.dir==="LONG"?"#16A34A":"#DC2626",fontWeight:"700"}}>✓</span><span style={{fontSize:"13px",fontWeight:"500"}}>{r}</span></div>))}</div></div></div>)}
          {tab==="signal"&&!analysis&&(<div style={{background:"white",borderRadius:"12px",padding:"50px 20px",textAlign:"center",border:"1px solid #E2E8F0"}}><div style={{fontSize:"52px",marginBottom:"12px"}}>🔬</div><div style={{fontSize:"17px",fontWeight:"700",marginBottom:"6px"}}>Ready to Analyze {sym}</div><div style={{fontSize:"14px",color:"#64748B"}}>Click <strong style={{color:"#1D4ED8"}}>Analyze</strong> for full ICT analysis</div></div>)}
          {tab==="sessions"&&(<div style={{display:"grid",gap:"10px"}}><div style={{background:"white",borderRadius:"12px",padding:"16px 18px",border:"1px solid #E2E8F0"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:"12px"}}><span style={{fontWeight:"700",fontSize:"16px"}}>🕐 Sessions — Mumbai IST</span><div style={{textAlign:"right"}}><div style={{fontWeight:"700",fontSize:"16px",color:"#1D4ED8",fontFamily:"monospace"}}>{istStr(istNow)}</div><div style={{fontSize:"11px",color:"#94A3B8"}}>{times.note}</div></div></div>{KZS.map(kz=>{const active=inWin(istNow,kz.start,kz.end),pct=active?winPct(istNow,kz.start,kz.end):0;return(<div key={kz.id} style={{background:active?`${kz.color}08`:"#FAFAFA",borderRadius:"10px",padding:"12px 14px",marginBottom:"7px",border:`2px solid ${active?kz.color:"#E2E8F0"}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{color:active?kz.color:"#94A3B8",fontWeight:active?"700":"500",fontSize:"14px"}}>{active?"● ":"○ "}{kz.name}</span><span style={{color:"#374151",fontFamily:"monospace",fontSize:"13px",fontWeight:"700",background:"#F1F5F9",padding:"2px 10px",borderRadius:"6px"}}>{kz.start}–{kz.end} IST</span></div>{active&&<><div style={{height:"5px",background:"#E2E8F0",borderRadius:"3px",marginTop:"8px"}}><div style={{height:"100%",width:`${pct}%`,background:kz.color,borderRadius:"3px",transition:"width 1s"}}/></div><div style={{display:"flex",justifyContent:"space-between",marginTop:"4px"}}><span style={{color:kz.color,fontSize:"12px",fontWeight:"600"}}>{kz.desc}</span><span style={{color:"#94A3B8",fontSize:"12px"}}>{pct}% elapsed</span></div></>}</div>);})}</div><div style={{background:"white",borderRadius:"12px",padding:"16px 18px",border:"1px solid #E2E8F0"}}><div style={{fontWeight:"700",fontSize:"16px",marginBottom:"12px"}}>🥈 Silver Bullet Windows</div>{SBS.map(sb=>{const active=inWin(istNow,sb.start,sb.end);return(<div key={sb.label} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 14px",background:active?"#F5F3FF":"#FAFAFA",borderRadius:"9px",marginBottom:"6px",border:`2px solid ${active?"#7C3AED":"#E2E8F0"}`}}><span style={{color:active?"#7C3AED":"#94A3B8",fontWeight:active?"700":"500",fontSize:"14px"}}>{active?"● ":"○ "}{sb.label}</span><span style={{color:"#374151",fontFamily:"monospace",fontSize:"13px",fontWeight:"700"}}>{sb.start}–{sb.end} IST</span>{active&&<span style={{background:"#7C3AED",color:"white",fontSize:"11px",padding:"2px 10px",borderRadius:"20px",fontWeight:"700"}}>ACTIVE</span>}</div>);})} <div style={{fontSize:"12px",color:"#92400E",marginTop:"8px",padding:"8px 12px",background:"#FFFBEB",borderRadius:"8px"}}>⚠️ After March 29: UK→BST → London shifts to 12:30 IST</div></div></div>)}
          {tab==="weights"&&(<div style={{display:"grid",gap:"10px"}}><div style={{background:"#EFF6FF",borderRadius:"12px",padding:"16px 18px",border:"1px solid #BFDBFE"}}><div style={{fontWeight:"700",fontSize:"15px",color:"#1D4ED8",marginBottom:"8px"}}>⚖️ What Are Weights & How Do They Improve?</div><div style={{fontSize:"13px",color:"#374151",lineHeight:"1.7"}}><p>Each ICT concept has a <strong>weight score (4–40)</strong>. Higher weight = more influence on signals.</p><p style={{marginTop:"6px"}}>When you run <strong>BT + Learn</strong>, the agent tracks which concepts led to wins vs losses:</p><ul style={{marginTop:"6px",paddingLeft:"18px"}}><li>Win rate &gt;70% → weight <span style={{color:"#16A34A",fontWeight:"700"}}>increased ↑</span> (concept is working)</li><li>Win rate &lt;50% → weight <span style={{color:"#DC2626",fontWeight:"700"}}>decreased ↓</span> (concept is unreliable)</li></ul><p style={{marginTop:"6px"}}>The agent runs this automatically after every backtest — it gets smarter each time.</p></div></div><div style={{background:"white",borderRadius:"12px",padding:"16px 18px",border:"1px solid #E2E8F0"}}><div style={{fontWeight:"700",fontSize:"15px",marginBottom:"4px"}}>Current Weights — Generation {brain.generations}</div><div style={{fontSize:"13px",color:"#64748B",marginBottom:"14px"}}>Sorted by influence. Green=boosted, Red=penalised, Grey=unchanged from default.</div>{Object.entries(brain.weights).sort((a,b)=>b[1].weight-a[1].weight).map(([k,rule])=>{const total=rule.wins+rule.losses,wr=total>0?Math.round(rule.wins/total*100):null,delta=rule.weight-(DW[k]?.weight||15);return(<div key={k} style={{marginBottom:"12px",padding:"10px 12px",background:"#F8FAFC",borderRadius:"8px",border:"1px solid #F1F5F9"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:"5px"}}><div><span style={{fontSize:"14px",fontWeight:"600"}}>{rule.label}</span><div style={{fontSize:"11px",color:"#94A3B8",marginTop:"2px"}}>{rule.info}</div></div><div style={{display:"flex",gap:"8px",alignItems:"center",flexShrink:0,marginLeft:"8px"}}>{wr!==null&&<span style={{fontSize:"12px",fontWeight:"600",color:wr>=60?"#16A34A":wr>=50?"#D97706":"#DC2626",background:wr>=60?"#F0FDF4":wr>=50?"#FFFBEB":"#FEF2F2",padding:"2px 8px",borderRadius:"20px"}}>{wr}% WR ({total})</span>}{delta!==0&&<span style={{fontSize:"13px",fontWeight:"700",color:delta>0?"#16A34A":"#DC2626"}}>{delta>0?"+":""}{delta}</span>}<span style={{fontWeight:"800",fontSize:"16px",color:"#1D4ED8",minWidth:"28px",textAlign:"right",fontFamily:"monospace"}}>{rule.weight}</span></div></div><div style={{height:"7px",background:"#E2E8F0",borderRadius:"4px"}}><div style={{height:"100%",width:`${Math.round((rule.weight/40)*100)}%`,background:delta>0?"#16A34A":delta<0?"#DC2626":"#94A3B8",borderRadius:"4px",transition:"width 0.5s"}}/></div></div>);})} </div></div>)}
          {tab==="learning"&&(<div style={{display:"grid",gap:"10px"}}>{learnLog.length>0&&(<div style={{background:"#F5F3FF",borderRadius:"12px",padding:"16px 18px",border:"1.5px solid #DDD6FE"}}><div style={{fontWeight:"700",fontSize:"15px",color:"#7C3AED",marginBottom:"10px"}}>🧠 Latest Learning Session</div>{learnLog.map((e,i)=><div key={i} style={{fontSize:"13px",padding:"5px 0",color:e.startsWith("↑")||e.startsWith("✅")||e.startsWith("📈")?"#16A34A":e.startsWith("↓")||e.startsWith("⚠️")?"#DC2626":"#374151",lineHeight:"1.6",borderBottom:i<learnLog.length-1?"1px solid #EDE9FE":"none"}}>{e}</div>)}</div>)}<div style={{background:"white",borderRadius:"12px",padding:"16px 18px",border:"1px solid #E2E8F0"}}><div style={{fontWeight:"700",fontSize:"15px",marginBottom:"10px"}}>📚 History ({brain.learningLog?.length||0} sessions)</div>{!brain.learningLog?.length&&<div style={{color:"#94A3B8",fontSize:"14px",textAlign:"center",padding:"28px"}}>No history yet. Click BT + Learn to start.</div>}{brain.learningLog?.map((s,i)=>(<div key={i} style={{background:"#F8FAFC",borderRadius:"10px",padding:"12px",marginBottom:"8px",border:"1px solid #E2E8F0"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:"5px"}}><span style={{color:"#7C3AED",fontWeight:"700",fontSize:"14px"}}>Gen {s.gen} · {s.sym}</span><span style={{color:"#94A3B8",fontSize:"12px"}}>{s.date}</span></div><div style={{display:"flex",gap:"12px",marginBottom:"4px"}}><span style={{color:s.winRate>=65?"#16A34A":s.winRate>=50?"#D97706":"#DC2626",fontWeight:"700",fontSize:"15px"}}>{s.winRate}% WR</span><span style={{color:"#64748B",fontSize:"13px"}}>{s.totalTrades} trades</span></div>{s.changes?.map((c,j)=><div key={j} style={{color:"#64748B",fontSize:"12px",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",marginTop:"2px"}}>· {c}</div>)}</div>))}</div></div>)}
          {tab==="backtest"&&btResult&&(<div style={{display:"grid",gap:"10px"}}><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:"10px"}}>{[{l:"WIN RATE",v:`${btResult.winRate}%`,c:btResult.winRate>=65?"#16A34A":btResult.winRate>=50?"#D97706":"#DC2626",bg:btResult.winRate>=65?"#F0FDF4":btResult.winRate>=50?"#FFFBEB":"#FEF2F2",border:btResult.winRate>=65?"#BBF7D0":btResult.winRate>=50?"#FDE047":"#FECACA"},{l:"TOTAL TRADES",v:btResult.total,c:"#1D4ED8",bg:"#EFF6FF",border:"#BFDBFE"},{l:"PROFIT FACTOR",v:btResult.profitFactor,c:btResult.profitFactor>=1.5?"#16A34A":"#DC2626",bg:btResult.profitFactor>=1.5?"#F0FDF4":"#FEF2F2",border:btResult.profitFactor>=1.5?"#BBF7D0":"#FECACA"},{l:"AVG R:R",v:btResult.avgRR,c:"#7C3AED",bg:"#F5F3FF",border:"#DDD6FE"}].map(x=>(<div key={x.l} style={{background:x.bg,borderRadius:"12px",padding:"14px",textAlign:"center",border:`2px solid ${x.border}`}}><div style={{color:"#94A3B8",fontSize:"11px",fontWeight:"600",letterSpacing:"0.5px",marginBottom:"7px"}}>{x.l}</div><div style={{color:x.c,fontWeight:"800",fontSize:"22px",fontFamily:"monospace"}}>{x.v}</div></div>))}</div><div style={{background:"white",borderRadius:"12px",padding:"14px 16px",border:"1px solid #E2E8F0",maxHeight:"280px",overflowY:"auto"}}><div style={{fontWeight:"700",fontSize:"14px",marginBottom:"10px"}}>Trade Log ({btResult.total} trades)</div>{btResult.trades.slice().reverse().map((t,i)=>(<div key={i} style={{display:"grid",gridTemplateColumns:"80px 80px 100px 70px 1fr",gap:"8px",padding:"8px 10px",background:i%2===0?"#F8FAFC":"white",borderRadius:"6px",fontSize:"13px",alignItems:"center",marginBottom:"2px"}}><span style={{color:t.outcome==="WIN"?"#16A34A":"#DC2626",fontWeight:"700"}}>{t.outcome==="WIN"?"✅ WIN":"❌ LOSS"}</span><span style={{color:t.dir==="LONG"?"#16A34A":"#DC2626",fontWeight:"600"}}>{t.dir==="LONG"?"▲ LONG":"▼ SHORT"}</span><span style={{color:"#1D4ED8",fontFamily:"monospace",fontWeight:"600"}}>@ {t.entry}</span><span style={{color:"#7C3AED",fontWeight:"700"}}>R:R {t.rr}</span><span style={{color:"#94A3B8",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{t.conf}% · {t.kzId}</span></div>))}</div></div>)}
          {tab==="backtest"&&!btResult&&(<div style={{background:"white",borderRadius:"12px",padding:"50px 20px",textAlign:"center",border:"1px solid #E2E8F0"}}><div style={{fontSize:"48px",marginBottom:"12px"}}>📊</div><div style={{fontSize:"17px",fontWeight:"700",marginBottom:"8px"}}>No Backtest Yet</div><div style={{fontSize:"14px",color:"#64748B"}}>Click <strong style={{color:"#7C3AED"}}>🧠 BT + Learn</strong> to test and improve the agent</div></div>)}
        </div>
        <div style={{display:"flex",flexDirection:"column",background:"white",borderLeft:"2px solid #E2E8F0"}}>
          <div style={{padding:"12px 16px",borderBottom:"2px solid #F1F5F9",background:"#FAFAFA"}}><div style={{fontWeight:"700",fontSize:"15px"}}>🤖 ICT AI Analyst</div><div style={{fontSize:"12px",color:"#64748B",marginTop:"2px"}}>Mumbai IST · Gen {brain.generations} · {isLive?`${liveCount}/4 Live`:"Sim"} · {activeKZ?activeKZ.name:"No active session"}{!aiKey&&<span style={{color:"#DC2626",marginLeft:"8px",fontWeight:"600"}}>⚠️ Add Anthropic key in ⚙️</span>}</div></div>
          <div style={{flex:1,overflowY:"auto",padding:"12px",display:"flex",flexDirection:"column",gap:"8px"}}>
            {chat.map((m,i)=>(<div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start"}}><div style={{maxWidth:"87%",padding:"10px 14px",borderRadius:m.role==="user"?"13px 13px 2px 13px":"13px 13px 13px 2px",background:m.role==="user"?"#1D4ED8":"#F8FAFC",color:m.role==="user"?"white":"#1E293B",fontSize:"14px",lineHeight:"1.6",whiteSpace:"pre-wrap",border:m.role==="assistant"?"1px solid #E2E8F0":"none",boxShadow:"0 1px 4px rgba(0,0,0,0.05)"}}>{m.content}</div></div>))}
            {chatLoading&&<div style={{display:"flex",gap:"5px",padding:"10px 14px",background:"#F8FAFC",borderRadius:"13px",width:"fit-content",border:"1px solid #E2E8F0"}}>{[0,1,2].map(i=><div key={i} style={{width:"8px",height:"8px",borderRadius:"50%",background:"#7C3AED",animation:`dot ${0.5+i*0.15}s infinite alternate`}}/>)}</div>}
            <div ref={chatRef}/>
          </div>
          <div style={{padding:"12px",borderTop:"2px solid #F1F5F9",display:"flex",gap:"8px"}}>
            <input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&!e.shiftKey&&handleChat()} placeholder={aiKey?"Ask about signals, sessions, ICT...":"Add Anthropic key in ⚙️ first"} style={{flex:1,background:"#F8FAFC",border:"2px solid #E2E8F0",borderRadius:"10px",padding:"10px 14px",color:"#1E293B",fontSize:"14px",outline:"none",fontFamily:"inherit"}} onFocus={e=>e.target.style.borderColor="#1D4ED8"} onBlur={e=>e.target.style.borderColor="#E2E8F0"}/>
            <button onClick={handleChat} disabled={chatLoading||!aiKey} style={{background:aiKey?"linear-gradient(135deg,#1D4ED8,#4338CA)":"#E2E8F0",color:aiKey?"white":"#94A3B8",border:"none",borderRadius:"10px",padding:"10px 18px",fontWeight:"700",cursor:aiKey?"pointer":"not-allowed",fontSize:"18px"}}>➤</button>
          </div>
          <div style={{padding:"0 12px 12px",display:"flex",gap:"6px",flexWrap:"wrap"}}>
            {["London KZ open?","Gold signal?","When NY opens?","Explain OTE","Liquidity sweep?","Best session?"].map(q=>(<button key={q} onClick={()=>setChatInput(q)} style={{background:"#F1F5F9",border:"1.5px solid #E2E8F0",color:"#64748B",borderRadius:"20px",padding:"4px 10px",fontSize:"12px",cursor:"pointer",whiteSpace:"nowrap",fontWeight:"500"}}>{q}</button>))}
          </div>
        </div>
      </div>
      <style>{`@keyframes dot{from{transform:scale(0.7);opacity:0.4}to{transform:scale(1.3);opacity:1}}::-webkit-scrollbar{width:5px;height:5px}::-webkit-scrollbar-track{background:#F1F5F9}::-webkit-scrollbar-thumb{background:#CBD5E1;border-radius:4px}::-webkit-scrollbar-thumb:hover{background:#94A3B8}select option{background:white;color:#1E293B}`}</style>
    </div>
  );
}
